// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.esupportail.sgc.services.crous;

import org.esupportail.sgc.services.crous.CrousRuleConfig;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CrousRuleConfig_Roo_Configurable {
    
    declare @type: CrousRuleConfig: @Configurable;
    
}
