// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.esupportail.sgc.domain;

import org.esupportail.sgc.domain.CardIdGenerator;

privileged aspect CardIdGenerator_Roo_JavaBean {
    
    public Long CardIdGenerator.getId() {
        return this.id;
    }
    
    public void CardIdGenerator.setId(Long id) {
        this.id = id;
    }
    
}
