// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.esupportail.sgc.domain;

import org.esupportail.sgc.domain.EsupNfcSgcJwsDevice;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EsupNfcSgcJwsDevice_Roo_Configurable {
    
    declare @type: EsupNfcSgcJwsDevice: @Configurable;
    
}
