// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.esupportail.sgc.domain;

import org.esupportail.sgc.domain.PayboxTransactionLog;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PayboxTransactionLog_Roo_Configurable {
    
    declare @type: PayboxTransactionLog: @Configurable;
    
}
